name: record
description: Audio recorder from microphone to file or stream with multiple codecs, bit rate and sampling rate options.
version: 6.1.2
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface: ^1.4.0
  record_web: ^1.2.0
  record_windows: ^1.0.7
  record_linux: ^1.2.1
  record_android: ^1.4.3
  record_ios: ^1.1.3
  record_macos: ^1.1.2

dev_dependencies:
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_ios
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_macos
      linux:
        default_package: record_linux
